version: '3'
services:
  db:
    image: postgres:latest  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'

  backend:
    build: 
      context: ./backend/second_part_backend
      dockerfile: Dockerfile.back
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.front
    ports:
      - '9000:9000'
    depends_on:
      - backend

volumes:  
  postgres_data: