# Generated by Django 4.2.7 on 2023-11-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_feature', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Romeo',
        ),
    ]
