# Generated by Django 4.2.7 on 2023-11-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_feature', '0002_rename_teacher_romeo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Romeo',
        ),
    ]
