# Generated by Django 4.2.7 on 2023-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_feature', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
