# Generated by Django 4.2.7 on 2023-11-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_feature', '0006_remove_querymodel_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryModel',
        ),
    ]
