# Generated by Django 4.2.7 on 2023-11-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_feature', '0009_savedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('saved_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories_feature.savedquery')),
            ],
        ),
    ]
