name: Run Docker application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker front image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.front
        push: false

    - name: Build and push Docker back image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/second_part_backend
        file: ./backend/second_part_backend/Dockerfile.back
        push: false

    - name: Run Docker container
      run: |
        export DB_NAME=${{ secrets.DB_NAME }}
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        export DB_HOST=${{ secrets.DB_HOST }}
        export DB_PORT=${{ secrets.DB_PORT }}
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        docker-compose up -d 
