name: Run Docker application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker front image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.front
        push: false

    - name: Build and push Docker back image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/second_part_backend
        file: ./backend/second_part_backend/Dockerfile.back
        push: false

    - name: Run Docker container
      run: |
        DB_NAME=${{ secrets.DB_NAME }} \
        DB_USER=${{ secrets.DB_USER }} \
        DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
        DB_HOST=${{ secrets.DB_HOST }} \
        DB_PORT=${{ secrets.DB_PORT }} \
        SECRET_KEY=${{ secrets.SECRET_KEY }} \
        GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} \
        docker-compose up -d 
 
